"""empty message

Revision ID: 585fc3715c5d
Revises: 
Create Date: 2019-05-28 13:35:05.364461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '585fc3715c5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('customer_code', sa.String(), nullable=True),
    sa.Column('create_date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
